name: docker build and deploy

on:
  push:
    branches:
      - main
    
env:
  AWS_REGION: ap-south-1
jobs:
  build-push-deploy:
    name: Build Push Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t "$ECR_URI:${GITHUB_SHA}" -t "$ECR_URI:latest" .

      - name: Push Docker Image
        run: |
          docker push "$ECR_URI:${GITHUB_SHA}"
          docker push "$ECR_URI:latest"

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment 

      - name: Wait for ECS Service
        run: |
          aws ecs wait services-stable \
            --cluster "$ECS_CLUSTER" \
            --services "$ECS_SERVICE" 
