name: StickyNotes Build Push Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: stickynotes-app-repo
  ECS_CLUSTER: app-cluster
  ECS_SERVICE: stickynotes-app-service
  ECS_TASK_DEFINITION: stickynotes-app-service
  CONTAINER_NAME: stickynotes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        run: |
          IMAGE=${{ steps.ecr.outputs.registry }}/${ECR_REPOSITORY}:latest

          docker build -t $IMAGE .
          docker push $IMAGE

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Create New Task Definition Revision
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query taskDefinition > task-definition.json

          python3 - <<'PY'
          import json
          import os

          with open("task-definition.json") as f:
              task = json.load(f)

          for key in [
              "taskDefinitionArn",
              "revision",
              "status",
              "requiresAttributes",
              "compatibilities",
              "registeredAt",
              "registeredBy"
          ]:
              task.pop(key, None)

          for container in task["containerDefinitions"]:
              if container["name"] == os.environ["CONTAINER_NAME"]:
                  container["image"] = os.environ["IMAGE"]

          with open("new-task-definition.json", "w") as f:
              json.dump(task, f)

          PY

          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json

      - name: Update Existing ECS Service
        run: |
          REVISION=$(aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query 'taskDefinition.revision' \
            --output text)

          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition ${ECS_TASK_DEFINITION}:${REVISION} \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Wait for ECS
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE

          echo "StickyNotes deployment completed"